---
title: "Math and Random Samples"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

## Scripting

Next we look at creating random samples of data in more detail, how we can run calculations on our data, and how we can replace values in our data.

In additional to mathematical operators, we will learn about the following functions:

* `sample()` and some of it\'s more specific variants `rnorm` and `runif`
* `replace()`

In doing so, we\'re also going to walk out of the console and move into a scripting environment.

<div class="question">
**Scripting**

By writing our code in a script, we can save our code and don\'t need to retype it every time we want to run it.

Scripting is really the first step to creating a reproducible environment for your work that also saves you time in the long run.

From your file menu, select *> New File* and *> R Script*. 

<span class="important">**This next bit is important**</span>

**Save your script on your desktop in a folder called `RScripts`**. This will be important later in this workshop.
</div>

## Simple math

R allows us to perform math on our data.

* \+
* \-
* \*
* /

This can be as simple as typing in

```{R}
2+2

2*3

3-2

4/2
```

But that\'s not overly exciting. We can get a little fancier:

```{R}
3^3

sqrt(81)

log(1200)

5%%2

4%%2
```

Still not terribly exciting, as this is basically just a glorified calculator. But let\'s look at this in more depth.

## Math on Vectors

**First** We know how to create a vector and assign that vector to a variable. So let\'s get some data prepped and try the following:

1. Create 2 vectors of equal length
2. Add them together with the results contained in a new variable.

```{R}
a <- c(1:5)
a

b <- c(6:10)
b

c <- a + b
c
```

**Second** Let's do another calculation on `c`, this time multiplication:

```{R}
d <- c * 5

d
```

<div class="note">
**Note**

Each time we\'re storing our new, computed data in a new variable.

If we\'re going to be running a computation on our data, for the purposes error tracking and transparency, it is advisable to generate a new variable.
</div>

This last example highlights an interesting feature of `R`. Vectorization is built into `R` from the ground up. To multiply every value in `c` by 5 where vectorization was not a reality, we\'d need to iterate the process.

```{R}
x <- vector() # create an empty vector to hold our results

for (i in 1:length(c)) { # for each element from 1 through to the length of c
  x[i] <- c[i] * 5 # multiply that element by 5 and pop it into x sequentially 
}

x # print the results
```

That is, we would need to painstakingly say, \"Here's an empty object ready to hold our computed data. Now, for every value in `c`, multiply that value by 5 and then iteratively put the result into the empty object--which then starts to fill up\".

This is partly why `R` is so nice, you don\'t need to know how to program--like how to loop through data--for basic applications! And yet, you get many of the benefits of a programming environment.

There\'s another key takeaway here. `R` frequently recycles data values. In the above example, 5 is it\'s own vector of data. When we hit the end of that vector, it\'s quantities are recycled until it matches the length of the longer vector it\'s being computed against. To see this perhaps a bit more clearly:

```{R}
short <- c(1,2)
long <- c(1:10)

unity <- short * long

short
long
unity
```


### What have we learned

* `R` can be used as a glorified calculator
* Mathematical functions are performed across a vector in `R`

## Conditions and Testing

Now we\'re going to look at how we can isolate or inquire about only a portion of our data.

To do this, we\'re gong to build a vector of 20 random numbers between 20 and 35, pretending that these are temperatures representing daily highs over a given period of time.

<div class = "note">
**sample()**

Generating sample data can be a great way of preparing your analyses in advance of doing data collection. When thinking about limiting bias in research design, the more that can be planned out in advance, the less of the overall process is being determined after study implementation in an ad hoc fashion; this is of particular importance in hypothesis testing confirmatory research. When doing exploratory research or data cleaning, sampling can support refining techniques on a smaller, more manageable data set.

While random sampling is a big topic, three common sampling functions that you\'ll find in `R` include `rnorm()` for normally distributed data generation, `runif()`, for uniformly distributed data generation, and `sample()`, for, well, basic sampling.
</div>

The `sample()` function takes four arguments

* a range to sample from
* the sample size
* a declaration of whether or not repeat selections are allowed
* a weighted probability

We apply the arguments in this pattern `sample(dataSource, sampleSize, repeatsAllowed, Probabilities)`

For this example, we\'ll ignore weighted probability.

```{R}
set.seed(120) ## makes things reproducible

dailyHighs <- sample(20:35, 20, replace = TRUE) # 20 samples with replacement between 20 and 35

dailyHighs
```

To get a bit more familiar with our sample, we\'ll test for values above a certain threshold, let\'s say above 27.

<div class = "question">
`R` allows testing of equivalence, using `<`, `>`, and `==`. Note that `5 = 5` is assignment, while `5 == 5` is a test.
</div>

Our first inclination might be to type the variable with a greater than sign in the hopes that `R` will tell you what values are greater than 27 in the variable.

Let's give that a try:

```{R}
dailyHighs > 27
```

So, this is interesting, and not exactly what we wanted.

This first statement is not showing us the **values**, but is apparently testing the **condition** and telling us if the condition--`dailyHighs` is greater than 27--is `TRUE` or `FALSE`. The output is a logical vector. We can confirm this

```{R}
is.vector(dailyHighs > 27)
```

Let's try this again a little differently:

```{R}
dailyHighs[dailyHighs > 27]
```

That's better. This time, we successfully asked the system to print out the values of our vector `dailyHighs` where it is true that `dailyHighs` is greater the 27.

An alternative approach would be to store the logical vector as it\'s own variable and then to pass that variable into `dailyHighs`.

```{R}
greaterThan27 <- dailyHighs > 27 ## assign the logical output of the > test to "greaterThan27"

dailyHighs[greaterThan27] ## print the values of dailyHighs where it is TRUE that the temps are higher than 27
```

We can explore this as a side by side too.

```{R, echo = FALSE}
sideBySide <- data.frame(dailyHighs, greaterThan27)
sideBySide
```

#### Indexing

What's happening here? Indexing. `R` maintains an index of the placement of your variable values in your data object. We ask about the value at a particular index using square brackets `[ ]`.

If we were to type

```{R}
dailyHighs[1]
```

`R` would return the first value in our vector. We can ask about any range within our vector. For example, the first three values:

```{R}
dailyHighs[1:3]
```

Or, like above, we can ask for a range based off of a condition, such as, all values where the variable `dailyHighs` is greater than 27.

```{R}
dailyHighs[dailyHighs > 27]

dailyHighs[greaterThan27]
```
In short:

```{R}
dailyHighs > 27 # is testing a condition that returns a logical value of TRUE or FALSE

dailyHighs[dailyHighs > 27] ## is inquiring about the indexed values that satisfy the condition

dailyHighs[greaterThan27] ## is the same as above, but storing the output of `dailyHighs > 27` inside of a new variable
```

## Exercise 3.3

1. How many of the values in `dailyHighs` are higher than 27:
2. Get a summary, similar to this, of the data in `daiylHighs`.

```{R, echo = FALSE}
summary(dailyHighs)
```

<div class="note">
**Note**

Your values will be different because our sampes are different, but the descriptive categories should be the same.
</div>

### What have we learned

* We can test a vector for a condition and logical vector in return
* We can retrieve the values from only a portion of the data in a vector. This subset of our data can be defined by:
  * an index point or range; or
  * a condition

## Replace()

Now that we know how to isolate values in our variables, we can start to manipulate portions of our data. To do this, we\'ll explore the `replace()` function.

`replace()` requires three arguments:

* a vector
* a list of index values to be replaced (or as a condition of the vector)
* a new value for replacement (this can be a computed value)

We\'ll start by replacing the first 3 temperatures with 0. 

And we apply the arguments in this pattern `replace(vector, list, value)`

```{R}
dailyHighs.zeroStart <- replace(dailyHighs, c(1,2,3), 0)

dailyHighs.zeroStart
```

Outcome: Not very exciting, but if we know where a value is in our vector, we can change it.

As we\'ve seen, one way that we can know where a value is located in our vector is to conditionally test for it.

And we\'ll do this by replacing all temperatures that are greater than 27 with 0. As quick reminder

```{R}
dailyHighs > 27 ## tests for a condition
```


```{R}
dailyHighs[dailyHighs > 27] ## while we can get a list of values where the condition is TRUE with this
```

Let's try this out.

```{R}
dailyHighs.gt27 <- replace(dailyHighs, dailyHighs > 27, 0) # in the variable dailyHighs, where the condition is TRUE, replace with 0

dailyHighs.gt27
```

alternatively, we use our stored variable `greaterThan27`

```{R}
dailyHighs.gt27 <- replace(dailyHighs, greaterThan27, 0)

dailyHighs.gt27
```

## Exercise 3.4

See if you can now add a bit of math into this scenario. Exactly as above, replace the temperatures in `dailyHighs` that are above 27, but this time, replace them with values that are double their own, so if you have 30, it becomes 60, 32 becomes 64 and so on. Your output should look like the following:

```{R, echo = FALSE}
dailyHighsMultiplied <- replace(dailyHighs, dailyHighs > 27, dailyHighs[dailyHighs > 27] * 2) ## Vector, condition, values where this condition is true * n

dailyHighsMultiplied
```

### What have we learned

* We can replace values in our data based either off of:
  * A known index point
  * A condition being met that allows an index point to be targeted
* We can perform multiple tasks in tandem, for example, replacing a value with a computed derivative of its original value.